export const GET_IMAGES_REQUEST = "GET_IMAGES_REQUEST";
export const GET_IMAGES_ERROR = "GET_IMAGES_ERROR";
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
export const GET_IMAGE_DETAILS = "GET_IMAGE_DETAILS";
export const GET_IMAGE_DETAILS_SUCCESS = "GET_IMAGE_DETAILS_SUCCESS";
export const GET_IMAGE_DETAILS_ERROR = "GET_IMAGE_DETAILS_ERROR";